# Generated by Django 2.2.4 on 2022-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShow', '0002_auto_20221219_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='showManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
