# Generated by Django 2.2.4 on 2022-12-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShow', '0003_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showManager',
        ),
    ]
